apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-job-belajar
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nodejs-job-belajar
          image: khannedy/nodejs-job