apiVersion: v1
kind: Pod
metadata:
  name: nginx-belajar-probe
  # labels:
  #   label-key1: label-value1
  # annotations:
  #   annotation-key1: annotation-value
  #   annotation-key2: veri long annotation value, bla bla bla bla bla bla
spec:
  containers:
    - name: nginx-belajar-probe
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5      # pertama kali pengecekan, mau nunggu berapa detik
        periodSeconds: 5            # pengecekan mau dicek setiap berapa kali. InCase : setiap 5 detik akan dilakukan pengecekan
        timeoutSeconds: 1           # jika mengembalikanya melebihi dari 1 second, maka dianggap tidak sehat
        successThreshold: 1         # jika dianggap sehat, mau berapa kali ngecek dianggap sehat
        failureThreshold: 3         # berapa kali pengecekan gagal sampai aplikasi diangggap tidak sehat dan harus di restart
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: 80
      #   initialDelaySeconds: 0
      #   periodSeconds: 10
      #   timeoutSeconds: 1
      #   successThreshold: 1
      #   failureThreshold: 3
      # startupProbe:
      #   httpGet:
      #     path: / 
      #     port: 80
      #   initialDelaySeconds: 0
      #   periodSeconds: 10
      #   timeoutSeconds: 1
      #   successThreshold: 1
      #   failureThreshold: 3